# Generated by Django 4.0.5 on 2022-06-14 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=20)),
                ('flag', models.CharField(default='1', max_length=2)),
                ('priority', models.CharField(default='0', max_length=2)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
